// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvmaompkcwqykanuvcpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2bWFvbXBrY3dxeWthbnV2Y3ByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NTEyNjMsImV4cCI6MjA3MjEyNzI2M30.4MubzVJbjZEdKGvmTgMukkmbakD5IB_S392Ar7L5q4Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});